favicon = "media/exampleSite/assets/images/templogo.png"
logo = "/images/templogo.png"
logo_darkmode = "/images/templogo.png"
logo_width = "160px"
logo_height = "32px"
logo_webp = true
logo_text = "Hugoplate"
navbar_fixed = true
theme_switcher = false
theme_default = "light"
mainSections = ["blog"]
contact_form_action = "#"
google_tag_manager = ""
google_adsense = ""
custom_script = ""
copyright = "Copyright 2026 Kenmore Presbyterian Church"
[preloader]
enable = false
preloader = ""
[navigation_button]
enable = true
label = "get a quote"
link = "contact"
[search]
enable = true
primary_color = "#121212"
include_sections = ["blog"]
show_image = true
show_description = true
show_tags = true
show_categories = true
[announcement]
enable = false
expire_days = 7
content = "<span class='text-center block'>♥️ Loving Hugoplate? <a class='underline' href='https://github.com/zeon-studio/hugoplate' target='_blank' rel='noopener'>Please ⭐️ on Github</a></span>"
[metadata]
keywords = ["Boilerplate","Hugo"]
description = "Hugo & Tailwindcss Starter"
author = "zeon.studio"
twitter = "zeon_studio"
image = "images/og-image.png"
[site_verification]
google = ""
bing = ""
baidu = ""
facebook = ""
mastodon = ""
[cookies]
enable = false
expire_days = 60
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"
[mermaid]
js_url = "https://cdn.jsdelivr.net/npm/mermaid@latest/dist/mermaid.esm.min.mjs"
[widgets]
sidebar = ["categories","tags"]
[google_map]
enable = false
map_api_key = "AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
[subscription]
enable = false
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074"
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"
